package com.example.inventorymanagementsystem.dao;

import com.example.inventorymanagementsystem.model.Item;
import com.example.inventorymanagementsystem.model.PerishableItem;
import com.example.inventorymanagementsystem.model.DurableItem;
import com.example.inventorymanagementsystem.util.DBConnection;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class ProductDAO {

    // 1. CREATE: Inserts a new product into your MySQL database table
    public boolean addProduct(Item item) {
        if (item == null) return false;

        String sql = "INSERT INTO products (name, price, stock_level, item_type, special_attribute) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, item.getName());
            pstmt.setDouble(2, item.getPrice());
            pstmt.setInt(3, item.getStockLevel());

            // Map the subclass type to a database string column
            if (item instanceof PerishableItem) {
                pstmt.setString(4, "PERISHABLE");
                pstmt.setString(5, ((PerishableItem) item).getExpiryDate());
            } else if (item instanceof DurableItem) {
                pstmt.setString(4, "DURABLE");
                pstmt.setString(5, ((DurableItem) item).getWarrantyPeriod());
            } else {
                pstmt.setString(4, "GENERAL");
                pstmt.setString(5, null);
            }

            int rowsInserted = pstmt.executeUpdate();

            // Retrieve the auto-increment ID generated by MySQL and assign it back to our object
            if (rowsInserted > 0) {
                try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        item.setId(generatedKeys.getInt(1));
                    }
                }
                return true;
            }
            return false;

        } catch (SQLException e) {
            System.err.println("Error adding product to MySQL database:");
            e.printStackTrace();
            return false;
        }
    }

    // 2. READ: Retrieves all rows from MySQL and maps them back into polymorphic Java objects
    public List<Item> getAllProducts() {
        List<Item> productList = new ArrayList<>();
        String sql = "SELECT * FROM products";

        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                double price = rs.getDouble("price");
                int stockLevel = rs.getInt("stock_level");
                String itemType = rs.getString("item_type");
                String specialAttr = rs.getString("special_attribute");

                // Reconstruct the correct inheritance child model based on the row flag
                if ("PERISHABLE".equalsIgnoreCase(itemType)) {
                    productList.add(new PerishableItem(id, name, price, stockLevel, specialAttr));
                } else if ("DURABLE".equalsIgnoreCase(itemType)) {
                    productList.add(new DurableItem(id, name, price, stockLevel, specialAttr));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error reading products from MySQL database:");
            e.printStackTrace();
        }
        return productList;
    }

    // 3. UPDATE: Permanently updates the stock level based on the row ID
    public boolean updateStock(int id, int newStock) {
        String sql = "UPDATE products SET stock_level = ? WHERE id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, newStock);
            pstmt.setInt(2, id);

            int rowsUpdated = pstmt.executeUpdate();
            return rowsUpdated > 0;

        } catch (SQLException e) {
            System.err.println("Error updating stock value in MySQL database:");
            e.printStackTrace();
            return false;
        }
    }
}